{{- if .Values.rbac.create }}
---
# IBM Confidential
# PID 5737-N85, 5900-AG5
# Copyright IBM Corp. 2022
#
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "synthetic-pop.clusterroleName" . }}
  labels:
    {{- include "synthetic-pop.commonLabels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "synthetic-pop.controllerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: {{ template "synthetic-pop.redisServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.browserscript.enabled }}
- kind: ServiceAccount
  name: {{ template "synthetic-pop.browserServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- if .Values.http.enabled }}
- kind: ServiceAccount
  name: {{ template "synthetic-pop.httpServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- if .Values.ism.enabled }}
- kind: ServiceAccount
  name: {{ template "synthetic-pop.ismServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
{{- if .Values.javascript.enabled }}
- kind: ServiceAccount
  name: {{ template "synthetic-pop.javascriptServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
roleRef:
  kind: ClusterRole
  name: {{ template "synthetic-pop.clusterroleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
