---
{{- if .Values.controller.enabled }}
{{- if .Values.controller.instanaKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "instanaKey.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic-pop.commonLabels" . | nindent 4 }}
type: Opaque
data:
  instana-key: {{ .Values.controller.instanaKey | b64enc | quote }}
{{- end }}
{{- end }}
{{- if and (.Values.imagePath | hasPrefix "containers.instana.io") (.Values.downloadKey) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: instana-io
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic-pop.commonLabels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecretInstanaIo" . }}
{{- end }}
{{- if and (not .Values.redis.tls.enabled) (.Values.redis.password) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "redis.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic-pop.commonLabels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ include "redis.password" . | b64enc | quote }}
{{- end }}
{{- if .Values.proxy.popProxyUserPass }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "proxyUserPass.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic-pop.commonLabels" . | nindent 4 }}
type: Opaque
data:
  proxy-user-pass: {{ .Values.proxy.popProxyUserPass | b64enc | quote }}
{{- end }}