---
# IBM Confidential
# PID 5737-N85, 5900-AG5
# Copyright IBM Corp. 2022
#
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "instanaKey.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic-pop.commonLabels" . | nindent 4 }}
type: Opaque
data:
  instana-key: {{ .Values.controller.instanaKey | b64enc | quote }}
{{- if .Values.imagePath | hasPrefix "containers.instana.io" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: instana-io
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic-pop.commonLabels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecretInstanaIo" . }}
{{- end }}
{{- if not .Values.redis.tls.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "redis.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic-pop.commonLabels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ include "redis.password" . | b64enc | quote }}
{{- end }}
{{- if .Values.proxy.popProxyUserPass }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "proxyUserPass.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic-pop.commonLabels" . | nindent 4 }}
type: Opaque
data:
  proxy-user-pass: {{ .Values.proxy.popProxyUserPass | b64enc | quote }}
{{- end }}