# IBM Confidential
# PID 5737-N85, 5900-AG5
# Copyright IBM Corp. 2022
#
{{- if .Values.serviceAccount.create }}
{{- if .Values.browserscript.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "synthetic-pop.browserServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic-pop.commonLabels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "synthetic-pop.controllerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic-pop.commonLabels" . | nindent 4 }}
automountServiceAccountToken: false
{{- if .Values.http.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "synthetic-pop.httpServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic-pop.commonLabels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
{{- if .Values.ism.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "synthetic-pop.ismServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic-pop.commonLabels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
{{- if .Values.javascript.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "synthetic-pop.javascriptServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic-pop.commonLabels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "synthetic-pop.redisServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic-pop.commonLabels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
