{{- if .Values.redis.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: synthetic-pop-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic-pop.commonLabels" . | nindent 4 }}
    app: redis
spec:
  type: ClusterIP
  ports:
    - name: synthetic-pop-redis-connect
      port: 6378
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis
{{- end }}
{{- if .Values.controller.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: synthetic-pop-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic-pop.commonLabels" . | nindent 4 }}
    app.kubernetes.io/name: controller
spec:
  type: ClusterIP
  ports:
    - name: synthetic-pop-controller-connect
      port: 8443
      targetPort: 8443
      protocol: TCP
  selector:
    app.kubernetes.io/name: controller
{{- end }}
