---
# IBM Confidential
# PID 5737-N85, 5900-AG5
# Copyright IBM Corp. 2022
#
apiVersion: v1
kind: Service
metadata:
  name: synthetic-pop-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - name: synthetic-pop-redis-connect
      port: 6378
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis